### PR TITLE
Updated ref links and include architecture diagram

### PR DESCRIPTION
**Pull request by lyndonlim27**
- Added chat history schema
- Updated broken links in overview.md
- Added in architecture diagram png

### CODE REVIEW

**Review by Wilsven — APPROVED** [review]

**Comment by Wilsven** [comment]
LGTM. Just need to fix the broken path. Let me know if you have issues.

**Comment by lyndonlim27** [comment]
> LGTM. Just need to fix the broken path. Let me know if you have issues.

I think it is because, the actual website path is not up yet. However i need to use the website URL path (https://synapxe-dna.github.io/technical-docs/projects/genai/conversational-assistant....) instead of local path as it causes error previously

**Comment by Wilsven** [comment]
> > LGTM. Just need to fix the broken path. Let me know if you have issues.
> 
> I think it is because, the actual website path is not up yet. However i need to use the website URL path (https://synapxe-dna.github.io/technical-docs/projects/genai/conversational-assistant....) instead of local path as it causes error previously

Alright. Thanks for pointing it out. I will overwrite the approval and merge. Do monitor this. Thank youu!

**Comment by lyndonlim27** [comment]
> > I think it is because, the actual website path is not up yet. However i need to use the website URL path (https://synapxe-dna.github.io/technical-docs/projects/genai/conversational-assistant....) instead of local path as it causes error previously
> 
> Alright. Thanks for pointing it out. I will overwrite the approval and merge. Do monitor this. Thank you!

Okay I have double check the link on the actual website and it works!

**Pull request merged**
