### PR TITLE
Kedro pipeline documentation for azure_rag

### PR DESCRIPTION
**Pull request by richmondsin**
- Added documentation for azure_rag pipeline.
- Added the documentation for the respective nodes.
- Added the overview page for how the pipeline works.
- Added the page for which articles were being removed.

### CODE REVIEW

**Review by Wilsven — CHANGES_REQUESTED** [review]
@richmondsin Are you certain these are ready to be merged into the `main` branch? I don't see any modifications made to the `mkdocs.yml`. 

Did you perhaps not run the `mkdocs` locally to check on this? Please consult the documentation.

**Comment by richmondsin** [comment]
> @richmondsin Are you certain these are ready to be merged into the `main` branch? I don't see any modifications made to the `mkdocs.yml`.
> 
> Did you perhaps not run the `mkdocs` locally to check on this? Please consult the documentation.

Will relook into it.

**Comment by richmondsin** [comment]
> > @richmondsin Are you certain these are ready to be merged into the `main` branch? I don't see any modifications made to the `mkdocs.yml`.
> > Did you perhaps not run the `mkdocs` locally to check on this? Please consult the documentation.
> 
> Will relook into it.

@Wilsven Edited the yml file.

**Review by Wilsven — APPROVED** [review]
@richmondsin Are you certain these are ready to be merged into the `main` branch? I don't see any modifications made to the `mkdocs.yml`. 

Did you perhaps not run the `mkdocs` locally to check on this? Please consult the documentation.

**Pull request merged**
